version: "3.7"

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:arm32v6
    restart: unless-stopped
    environment:
      API_KEY: "${API_KEY}"
      ZONE: "${ZONE}"
      SUBDOMAIN: "${SUBDOMAIN}"
      CRON: "*/1 * * * *"
    env_file:
      - .env
